[package]
name = 'ngconverter-wasm'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['cdylib']

[dependencies]
anyhow = '1.0.65'
quick-xml = '0.25.0'
wasm-bindgen = '0.2.83'

[profile.release]
panic = 'abort'
lto = true
opt-level = 'z'
codegen-units = 1
